version: '3.7'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: password
    container_name: go_db
    ports:
      - "3306:3306"
    tty: true
    volumes:
      - beego-boilerplate-mysql:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
  app:
    build:
      context: .
    volumes:
      - ".:/app"
    container_name: go_app
    ports:
      - "8080:8080"
      - "8088:8088"
    tty: true
    depends_on:
      - db
    command: bee run
volumes:
  beego-boilerplate-mysql:
    driver_opts: 
      type: none
      device: ${PWD}/.docker/volumes/db
      o: bind